# Generated by Django 3.0.4 on 2020-04-22 09:51

from django.db import migrations, transaction, DatabaseError
from dataedit.models import Table
from api.actions import get_comment_table, has_table
from dataedit.management.commands.mirror import migrate

def migrate_metadata(apps, schema_editor):
    success = migrate(check=True, verbose=False)
    if not success:
        raise DatabaseError("Database and models do not align. Please run `manage.py mirror --check` for more information.")
    try:
        with transaction.atomic():
            for table in Table.objects.all():
                if has_table(dict(schema=table.schema.name, table=table.name)):
                    table.metadata = get_comment_table(table.schema.name, table.name)
                    table.save()
    except:
        print("An error occured during the migration of metadata")
        raise


def migrate_metadata_rev(apps, schema_editor):
    try:
        with transaction.atomic():
            for table in Table.objects.all():
                if has_table(dict(schema=table.schema.name, table=table.name)):
                    table.metadata = None
                    table.save()
    except:
        print("An error occured during the migration of metadata")
        raise


class Migration(migrations.Migration):

    dependencies = [
        ('dataedit', '0014_auto_20200422_1151'),
    ]

    operations = [
        migrations.RunPython(migrate_metadata, reverse_code=migrate_metadata_rev)
    ]
